# Routes du site Mord ton Pion

[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "templates/accueil.html"

[[routes]]
url = "equipes"
controleur = "controleurs/equipes.py"
template = "templates/equipes.html"

[[routes]]
url = "creer_equipe"
controleur = "controleurs/creer_equipe.py"
template = "templates/creer_equipe.html"

[[routes]]
url = "partie_normale"
controleur = "controleurs/partie_normale.py"
template = "templates/partie_normale.html"

[[routes]]
url = "partie_avancee"
controleur = "controleurs/partie_avancee.py"
template = "templates/partie_avancee.html"

[[routes]]
url = "historique"
controleur = "controleurs/historique.py"
template = "templates/historique.html"
