[[routes]]
url = ""
controleur = "controleurs/hello.py"
template = "templates/hello.html"
# DÃ©finition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template
