# DÃ©finition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

#	[[routes]]
#	url = ""
#	controleur = "controleurs/accueil.py"
#	template = "templates/accueil.html"
#
#	[[routes]]
#	url = "afficher"
#	controleur = "controleurs/afficher.py"
#	template = "templates/afficher.html"
#
#<	[[routes]]
#	url = "rechercher"
#	controleur = "controleurs/rechercher.py"
#	template = "templates/rechercher.html"
#
#	[[routes]]
#	url = "historique"
#	controleur = "controleurs/historique.py"
#	template = "templates/historique.html"
#
#	[[routes]]
#	url = "ajouter"
#	controleur = "controleurs/ajouter.py"
#	template = "templates/ajouter.html" 


[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "templates/accueil.html"

[[routes]]
url = "equipes"
controleur = "controleurs/equipes.py"
template = "templates/equipes.html"

[[routes]]
url = "creer_equipe"
controleur = "controleurs/creer_equipe.py"
template = "templates/creer_equipe.html"

[[routes]]
url = "partie_normale"
controleur = "controleurs/partie_normale.py"
template = "templates/partie_normale.html"

[[routes]]
url = "partie_avancee"
controleur = "controleurs/partie_avancee.py"
template = "templates/partie_avancee.html"

[[routes]]
url = "historique"
controleur = "controleurs/historique.py"
template = "templates/historique.html"

